### ISSUE TITLE
S-model VVM325

### ISSUE THREAD

**Issue by latisen** [yozik04/nibe#7]
Creating this thread to solve issues and make it work with the S-model VVM325

Regular manual: https://www.nibe.eu/assets/documents/14743/331115-1.pdf
Modbus manual: https://www.nibe.eu/download/18.3db69dc1795e0d992c5722/1622634529178/Modbus%20S-series%20EN%20M12676EN-1.pdf

@yozik04 : Is this sufficient? I have a contact at NIBE technical department in sweden that I can probably get more information from :)

**Comment by yozik04** [comment]
You need to show the code.

**Comment by latisen** [comment]
> You need to show the code.

This:
`import asyncio
import logging

from nibe.coil import Coil
from nibe.connection.modbus import Modbus
from nibe.heatpump import HeatPump, Model

logger = logging.getLogger("nibe").getChild(__name__)


def on_coil_update(coil: Coil):
    logger.debug(f"on_coil_update: {coil.name}: {coil.value}")


async def main():
    heatpump = HeatPump(Model.VVM325)
    heatpump.initialize()

    heatpump.subscribe(HeatPump.COIL_UPDATE_EVENT, on_coil_update)

    connection = Modbus(heatpump=heatpump, url="tcp://10.0.1.15:502", slave_id=1)

    coil = heatpump.get_coil_by_address('30009')
    await connection.read_coil(coil)

    logger.debug(f"main: {coil.name}: {coil.value}")


if __name__ == '__main__':
    logging.basicConfig(level=logging.DEBUG)

    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
    loop.run_forever()`

**Comment by yozik04** [comment]
can it be that another nibe library is installed locally?

**Comment by rtitmuss** [comment]
If you look on page 7 of the modbus manual there are instructions to
download the available registers on a USB stick. Maybe that will help
verify which registers are available on your heat pump.

**Comment by latisen** [comment]
Accidantaly ran the file from the wrong dir. Now the error says:

DEBUG:asyncio:Using proactor: IocpProactor
DEBUG:nibe.nibe.connection.modbus:Sending read request
DEBUG:sockio.TCP(10.0.1.15:502):open connection (#1)
Traceback (most recent call last):
  File "c:\Users\dick\OneDrive - AFRISO EMA AB\Dokument\nibe\dick_test.py", line 33, in <module>
    loop.run_until_complete(main())
  File "C:\Users\dick\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\Users\dick\OneDrive - AFRISO EMA AB\Dokument\nibe\dick_test.py", line 24, in main
    await connection.read_coil(coil)
  File "c:\Users\dick\OneDrive - AFRISO EMA AB\Dokument\nibe\nibe\connection\modbus.py", line 25, in read_coil
    result = await asyncio.wait_for(
  File "C:\Users\dick\AppData\Local\Programs\Python\Python39\lib\asyncio\tasks.py", line 479, in wait_for
    return fut.result()
  File "C:\Users\dick\AppData\Local\Programs\Python\Python39\lib\site-packages\async_modbus\core.py", line 194, in read_input_registers
    return await self._send_message(request)
  File "C:\Users\dick\AppData\Local\Programs\Python\Python39\lib\site-packages\async_modbus\core.py", line 142, in _send_message
    return await self.protocol._async_send_message(
  File "C:\Users\dick\AppData\Local\Programs\Python\Python39\lib\site-packages\async_modbus\core.py", line 39, in send_message_tcp
    await writer.drain()
  File "C:\Users\dick\AppData\Local\Programs\Python\Python39\lib\site-packages\async_modbus\core.py", line 113, in drain
    await self._write_coro
  File "C:\Users\dick\AppData\Local\Programs\Python\Python39\lib\site-packages\sockio\aio.py", line 31, in wrapper
    await self.open()
  File "C:\Users\dick\AppData\Local\Programs\Python\Python39\lib\site-packages\sockio\aio.py", line 287, in open
    self.reader, self.writer = await coro
  File "C:\Users\dick\AppData\Local\Programs\Python\Python39\lib\site-packages\sockio\aio.py", line 158, in open_connection
    configure_socket(sock, no_delay=no_delay, tos=tos, keep_alive=keep_alive)
  File "C:\Users\dick\AppData\Local\Programs\Python\Python39\lib\site-packages\sockio\aio.py", line 117, in configure_socket
    sock.setsockopt(socket.SOL_IP, socket.IP_TOS, tos)
  File "C:\Users\dick\AppData\Local\Programs\Python\Python39\lib\asyncio\trsock.py", line 82, in setsockopt
    self._sock.setsockopt(*args, **kwargs)
OSError: [WinError 10022] Ett ogiltigt argument angavs (Invalid argument)

**Comment by latisen** [comment]
seems to be something with the modbus connection

**Comment by latisen** [comment]
I'm up and running. Installed python and all req's on another Pi. about 40% of the sensors for VVM325S is added now.

**Comment by latisen** [comment]
Just want to test writing. How do I write to a coil?

**Comment by yozik04** [comment]
Cool! Does it read all these 40% of sensors?

**Comment by yozik04** [comment]
Update coil value and execute:
await connection.write_coil(coil)

**Comment by elupus** [comment]
What is the status here? Would be cool to add the modbus support to home assistant native client, but we'd need a guinea pig.

**Comment by yozik04** [comment]
Would be great but nobody tested it yet as I know.

**Comment by elupus** [comment]
@latisen can you export the csv of registers from your pump and post here. I think it should be same way as this manual: https://www.nibe.eu/download/18.3db69dc1795e0d992c5722/1622634529178/Modbus%20S-series%20EN%20M12676EN-1.pdf

Ps. Switch the pump to english first.

**Comment by elupus** [comment]
This is supported now.
